// Generated by https://quicktype.io

export interface GetAllTripsResponse {
    content: Trip[];
    pageable: Pageable;
    last: boolean;
    totalPages: number;
    totalElements: number;
    size: number;
    number: number;
    sort: Sort;
    first: boolean;
    numberOfElements: number;
    empty: boolean;
}

export interface Trip {
    id: string;
    departurePlace: string;
    arrivalPlace: string;
    departureTime: string;
    estimatedDuration: number;
    arrivalTime: string;
    price: number;
    tripDescription: string;
}

export interface Pageable {
    pageNumber: number;
    pageSize: number;
    sort: Sort;
    offset: number;
    paged: boolean;
    unpaged: boolean;
}

export interface Sort {
    empty: boolean;
    sorted: boolean;
    unsorted: boolean;
}
