name: sharetravel_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.5.0
  shared_preferences: ^2.2.2
  chopper: ^7.1.1
  chopper_generator: ^7.1.1
  provider: ^6.1.1
  get: ^4.6.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  http: ^1.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sharetravel_logo.png
    - assets/sharetravel_logo_text.png
    - assets/ilustration.png
    - assets/ilustration_filter.png
    - assets/green_arrow.png
    - assets/fonts/Nunito-Regular.ttf
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
